imageName: registry.access.redhat.com/ubi8/ubi-minimal:latest
jobOutputFileEnvVar: JOB_OUTPUT
uniqueValue: hello world


service:
  initCommand: [/bin/bash, -c, 'for n in $(seq 5); do [ -f $JOB_OUTPUT ] && exit 0 || sleep 10 ]; done ; exit 1']
  initCommandArgs:
  mainCommand:
  mainCommandArgs: [sleep, infinity]
  readinessCommand: []
  resources: {}

job:
  command: [/bin/bash, -c, 'sleep 30 ; date > $JOB_OUTPUT']
  commandArgs:
  resources: {}
  retries: 0
  timeout: 900

resources:
  job:
    limits:
      cpu: 10m
      memory: 32Mi
  deployment:
    limits:
      cpu: 10m
      memory: 32Mi
    